### ISSUE TITLE
community_loader_sites ant task fails

### ISSUE THREAD

**Issue by mcdan** [Adobe-Marketing-Cloud/aem-demo-machine#14]
```
community_loader_sites:
     [echo] Loading Community Site Templates (for AEM 6.1 FP4 and beyond)
     [java] running com.adobe.aem.demomachine.communities.Loader with default permissions (exit forbidden)
     [java] Running in same VM Executing 'com.adobe.aem.demomachine.communities.Loader' with arguments:
     [java] '-h'
     [java] 'localhost'
     [java] '-p'
     [java] '4502'
     [java] '-u'
     [java] 'admin'
     [java] '-a'
     [java] '4503'
     [java] '-f'
     [java] '/Users/mcweeney/github/Adobe-Marketing-Cloud/aem-demo-machine/dist/community/sites/loader-site-templates-fp4.csv'
     [java] '-c'
     [java] '-r'
     [java] 
     [java] The ' characters around the executable and arguments are
     [java] not part of the command.
Checking for listener at localhost:4503
     [echo] Loading Community sites (and publishing)...
     [java] running com.adobe.aem.demomachine.communities.Loader with default permissions (exit forbidden)
     [java] Running in same VM Executing 'com.adobe.aem.demomachine.communities.Loader' with arguments:
     [java] '-h'
     [java] 'localhost'
     [java] '-p'
     [java] '4502'
     [java] '-u'
     [java] 'admin'
     [java] '-a'
     [java] '4503'
     [java] '-f'
     [java] '/Users/mcweeney/github/Adobe-Marketing-Cloud/aem-demo-machine/dist/community/sites/loader-sites.csv'
     [java] '-c'
     [java] '-r'
     [java] 
     [java] The ' characters around the executable and arguments are
     [java] not part of the command.

BUILD FAILED
/Users/mcweeney/github/Adobe-Marketing-Cloud/aem-demo-machine/build.xml:3474: Java returned: -1
    at org.apache.tools.ant.taskdefs.Java.execute(Java.java:111)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:154)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.Main.runBuild(Main.java:851)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

Total time: 1 second
```

Seems to have been introduced since 95c7062dd04be15fa8e2bb464706e743387cb982 as backing up to that point in git makes the task run cleanly.

**Comment by mcdan** [comment]
NM, this is actually due to a problem in the latest soco package.
